version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    executor: aws-cli/default
    resource_class: medium
    steps:
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          #remote-docker-version: '20.10.21'
          remote-docker-layer-caching: true
            
 

            