version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-cli: circleci/aws-cli@2.0
workflows:
  testing:
    jobs:
      - build
jobs:
  build:
    executor: aws-cli/default
    resource_class: medium
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME	
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: false
          dockerfile: Dockerfile
          path: .
          region: AWS_DEFAULT_REGION	
          registry-id: AWS_ECR_REGISTRY_ID
          repo: testing
          tag: 'yaash'
          setup-remote-docker: true
          remote-docker-version: '20.10.21'
          remote-docker-layer-caching: true 
