version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - hello-job
jobs:
  runner-test:
    machine: true
    resource_class: yashdeb/circleci-runner
    steps:
      - run: |
           mysql -h database-1.cnara9ato1ex.ap-south-1.rds.amazonaws.com -u $yash_Database_Name -p$Mysql_pass
           SHOW DATABASES;   
  hello-job:
    docker:
      - image: cimg/node:17.2.0 
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run: echo "hello world" 
            
            