version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-cli: circleci/aws-cli@2.0

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - setup_remote_docker: 
          version: 20.10.21    
workflows:
  version: 2
  testing:
    jobs:
      - test
      #- build