version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: yashdeb/circleci-runner
    steps:
      - run: mysql -h database-1.cnara9ato1ex.ap-south-1.rds.amazonaws.com -u admin -p ilugoel1