version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - hello-job
jobs:
  runner-test:
    machine: true
    resource_class: yashdeb/circleci-runner
    steps:
      - run: 
          command: |
           echo $(sh test.sh)
  hello-job:
    docker:
      - image: cimg/node:17.2.0 
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run: echo "hello world" 
            
            