version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  testing:
    jobs:
      - test
      - runner-test
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"  
  runner-test:
    executor: aws-cli/default
    resource_class: medium
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-cli-version: latest
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: .
          #executor: aws-ecr/default
          no-output-timeout: 20m
          path: .
          platform: linux/amd64
          profile-name: myProfileName
          public-registry: false
          push-image: true
          region: AWS_DEFAULT_REGION
          #registry-id: AWS_ECR_REGISTRY_ID
          repo: myECRRepository
          setup-remote-docker: true
          remote-docker-version: '20.10.21'
          remote-docker-layer-caching: true
            
 

            